### ISSUE TITLE
Alphabetization of Macros

### ISSUE THREAD

**Issue by lucasortizny** [teamradish/TRTwitchPlaysBot#16]
For Bacon's request (and I endorse it), a way for when listing the macros in a chat with !macros for them to be alphabetized so it's a little easier to read. I assume right now they are printed based on the order in which they were added?

**Comment by tdeeb** [comment]
Yes, that's true. Sorting them lexicographically makes more sense from a readability perspective, and I'll get on this soon.

**Comment by tdeeb** [comment]
Completed in https://github.com/teamradish/TRTwitchPlaysBot/commit/1107b78e38fb92f4f9326615afcf4928b0d7c3b5.
