### ISSUE TITLE
Move data handling to a database

### ISSUE THREAD

**Issue by tdeeb** [teamradish/TRTwitchPlaysBot#17]
As the amount of bot data and settings grow, it's becoming harder to manage. Consider using a database such as MySQL to better handle all this data. There can be models for macros, game logs, users, and the rest.

**Comment by lucasortizny** [comment]
I would be interested in assisting for some of this. I would need to learn the C# syntax prior to this though.

**Comment by tdeeb** [comment]
I have no experience using a database in .NET. Ideally the database should be as painless to handle as possible by having as much of it inside the bot. `System.Data.SqlConnection` may be a good start ([Example](https://stackoverflow.com/questions/43825626/how-to-connect-to-sql-server-from-net-core-without-using-entity-framework)).

If anyone else has experience with this, feel free to chime in.

**Comment by taximadish** [comment]
I've used the SQLite NuGet package for stuff like this in the past, seems like it'd be a really good fit here. Much less painful than a regular database, would recommend :)

**Comment by tdeeb** [comment]
@taximadish Is it [this](https://www.nuget.org/packages/System.Data.SQLite) package? SQLite sounds like a good fit since it's embedded.

**Comment by taximadish** [comment]
Yep, that's the one.

**Comment by lucasortizny** [comment]
My thinking was that maybe we can begin with this as an optional feature that can be configured in settings. Like giving the user the option to connect to a database (making sure full perms are granted) so that the program can automatically create the tables necessary for it. Then maybe in the future integrate it upon installation and phase out the old way of doing it.

**Comment by tdeeb** [comment]
I agree. We should also have the new config (https://github.com/teamradish/TRTwitchPlaysBot/issues/18) able to import the old settings files into the database.

**Comment by lucasortizny** [comment]
Can you elaborate on what you mean by that? Do you also want the entire settings to be configured via the Database for the long-term goal?

**Comment by tdeeb** [comment]
Yeah, my thinking is after adding the database and config GUI, there's an option to import the settings files (**BotData.txt**, **Settings.txt**) into the database.

**Comment by tdeeb** [comment]
@lucasortizny Have you been using SQLite for this? As an example of how simple it is for the end user, the [ChatterBot](https://github.com/teamradish/TRTwitchPlaysBot/blob/master/TRBot/TRBotCore/Supplementary/ChatterBot.py) instance already uses one. It stores all the data in a database, and the user doesn't need to run a database server or handle credentals to use the ChatterBot instance.

**Comment by lucasortizny** [comment]
hey @tdeeb ! I am using it, I installed the package via the command line. One of the things I did notice after I committed the database credentials being added to the settings class was that it is all saved locally. I am gonna remove it in a future commit and just have a true/false boolean value in the settings class as the only option~

**Comment by tdeeb** [comment]
Bumped this up in priority. The sooner it's in, the better.

**Comment by lucasortizny** [comment]
Hey Kimi, I'm gonna ask that you take over this issue. I haven't had a chance to code much in the last couple of weeks due to me struggling with some personal issues. Sorry about that:(

**Comment by TwitchPlaysSpeedruns** [comment]
Very interested in this, this was a stumbling block for me in my original code. Handling things server side would be a game changer.

**Comment by tdeeb** [comment]
Since TRBot 2.0 will have a lot of breaking changes already, I'm considering implementing this for it to make things easier to handle, especially since there's even more data than before, such as consoles. It will need to ship with a way to modify the data, preferably something along the lines of https://github.com/teamradish/TRTwitchPlaysBot/issues/18.

**Comment by tdeeb** [comment]
The database is set up and working, complete with migrations. Currently it stores settings, game logs, and savestate logs. The next major task is to get the rest of the data in there. Some of the data will depend on https://github.com/teamradish/TRTwitchPlaysBot/issues/25.

**Comment by tdeeb** [comment]
This has been completed and will be in the 2.0 release. I'm currently held up by the following bug in Entity Framework Core: https://github.com/dotnet/efcore/issues/23180

A fix is in another branch, so I will wait for it to get into the next release. At worst, I can compile from source and use that version.
