### ISSUE TITLE
System Config GUI

### ISSUE THREAD

**Issue by SeniorFluffie** [teamradish/TRTwitchPlaysBot#18]
A GUI to manage all the various options, and config files would be really useful. There are tons of commands that are not as easily accessible as well as spread across various files. Having a GUI to manage things like bot data, user data, the current console, game messages, etc. would be extremely useful and would be relatively easy to implement. Just a simple HTML file with decent styling seems like a game changer. This could also be used to manage controller configs with static dropdown menus based on VJoy, etc.

**Comment by tdeeb** [comment]
Thanks for your suggestion. This will likely come after https://github.com/teamradish/TRTwitchPlaysBot/issues/17.

**Comment by tdeeb** [comment]
Hey @SeniorFluffie, we have just released TRBot 2.0, which uses a SQLite database instead. There are many SQLite viewers available, so I no longer feel this is necessary and thus am closing out this issue.

With this release, we also have more thorough documentation and a [guide for managing data](https://github.com/teamradish/TRTwitchPlaysBot/blob/master/Wiki/Managing-Data.md) that can aid in finding and modifying the settings you're looking for.
