### ISSUE TITLE
Basic Twitch Chat Overlay

### ISSUE THREAD

**Issue by SeniorFluffie** [teamradish/TRTwitchPlaysBot#19]
Simply providing an option to display the chat messages parsed by TRBot (as well as an option for valid commands or all chat messages) would be very useful. By merely putting in another window, it would be very easy / simple to capture that as a window for streaming software like OBS. The idea is to use the same format as current chat overlays, as it is very simple to implement and use. Individuals who need the more advanced / customizable chat overlays will inevitably end up using them.

**Comment by tdeeb** [comment]
Closing out on GitHub - [see the associated issue on the new main repo](https://codeberg.org/kimimaru/TRBot/issues/19).
