### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by tdeeb** [teamradish/TRTwitchPlaysBot#20]
Create unit tests using [NUnit](https://nunit.org/). Some tests could include:

* Parser output using many different sample inputs.
* Adding/removing macros, memes, etc.

It would be better to have a separate project for the tests so the code doesn't get muddled.

**Comment by lucasortizny** [comment]
Would this be something we want after a database implementation?

**Comment by tdeeb** [comment]
Not necessarily, but it may be preferable. Having the database implemented would let us test the database itself.

**Comment by tdeeb** [comment]
Some of the code is hard to test due to tight coupling. For example, `Parser.ParseInputs` is coupled to reading bot data. I'll start on improving this.

**Comment by tdeeb** [comment]
I made the necessary changes and added a project for conducting tests. I'll double-check everything and add documentation on how to run the tests later.

**Comment by tdeeb** [comment]
The unit test project and several Parser tests were merged into develop with https://github.com/teamradish/TRTwitchPlaysBot/commit/9078a9e9ec40189d05f442aa342281e11618f1ae.
