### ISSUE TITLE
Delays with the Chatbot

### ISSUE THREAD

**Issue by lucasortizny** [teamradish/TRTwitchPlaysBot#21]
Currently there is a significant delay in the !chat command for the bot. I am wondering if the sample size change is causing it or something? The messages are sent like 40-60 seconds late. It can be replicated via any usage of the !chat command in the tppm channel (this might be a specific issue to this version but I wanna open an issue just in case others might find the same issue in the future)

**Comment by tdeeb** [comment]
I'm not sure what's causing the delay in this instance, but the ChatterBot interaction needs a complete rewrite anyway. Right now it's [reading/writing from/to](https://github.com/teamradish/TRTwitchPlaysBot/blob/cd8e6625af0ef62f017f428ec23087b96b356462/TRBot/TRBotCore/Classes/Commands/ChatBotCommand.cs) files to get the response. There is an artificial delay to allow for enough time for the response to go through. However, this means that if multiple people try to talk with it in this time, it will respond to only one of them. The response will also be delayed if there is a lock on one of the files.

The challenge would be to find a reliable way to interact with the Python code so we can pass along prompts and get back responses.

**Comment by tdeeb** [comment]
Regarding the delay: that instance was trained with some of the Ubuntu Dialogue Corpus, which greatly increases the response time. Deleting the database and retraining it with the ChatterBot Corpus Trainer restores the response time to its original speed.

**Comment by lucasortizny** [comment]
Okie dokie, I think it is fair to close this issue then
