### ISSUE TITLE
Setting up the Dev Environment

### ISSUE THREAD

**Issue by lucasortizny** [teamradish/TRTwitchPlaysBot#23]
I was wondering if it was fine to have a small README for installing the dev environment for potential future contributors. Something to make it a little easier for new contributors (this might be coming from me lmao). But it could be a good step in the right direction for making this project open-sourced

**Comment by tdeeb** [comment]
I've added more [details about building from source](https://github.com/teamradish/TRTwitchPlaysBot/wiki/Getting-Started#building-from-source) to the wiki. Does this help?

**Comment by lucasortizny** [comment]
Yep thank you!
