### ISSUE TITLE
Add the ability to play MIDI notes

### ISSUE THREAD

**Issue by tdeeb** [teamradish/TRTwitchPlaysBot#26]
This can allow viewers to play music on the stream. It should be an option that the bot can enable or disable at will.

An example of the syntax would be `!music d2 a3 c2`. We may have to add additional syntax for timing, but for now hardcoding the timing should suffice.

Potential libraries:

- [managed-midi](https://github.com/atsushieno/managed-midi) - Cross-platform .NET MIDI processing library.
- [cxxmidi](https://github.com/5tan/cxxmidi) - C++ MIDI Library. Runs on Windows and Linux.

**Comment by TwitchPlaysSpeedruns** [comment]
We would deffo use this. Could add different instruments. Players could collab. Used to do something similar in LOTR online using ABC files. I say this with zero knowledge of the code or how hard this would be.

**Comment by tdeeb** [comment]
Closing out on GitHub - [see the associated issue on the new main repo](https://codeberg.org/kimimaru/TRBot/issues/26).
