### ISSUE TITLE
Feature request (TPS)

### ISSUE THREAD

**Issue by TwitchPlaysSpeedruns** [teamradish/TRTwitchPlaysBot#32]
Since you so kindly offered =)

Would it be possible to have a !teamsmode function?

This would place the bot in teamsmode.
Every new player that enters chat is assigned to either controller 1 or 2. The bot alerts them as to their team. 
(I'm aware players can choose this option using !player or using "&2" but this is a lot to ask of viewers in my experience.)

Now every player who inputs in chat is auto assigned to controller 1 or controller 2. 
Now we would need some way of balancing the numbers so neither side gets too populated in relation to the other. 
Players could have a !swapteam option which people can accept or deny to switch teams. 

How I'd use this;

2 versions of GBA emulator set up on stream with Pokemon Red on one and Leaf Green on the other. Controller 1 set to Leaf Green, controller 2 to Fire red.
2 versions of livesplit with inputs set to relative controllers (ss5) with nextsplit options (!addsyn nextsplit ss5). 
Players are assigned teams randomly and race each other.

**Comment by TwitchPlaysSpeedruns** [comment]
You might be interested to know this dude got a Twitchplays ps4 working with your code - https://www.twitch.tv/smurfbox

**Comment by tdeeb** [comment]
Completed in https://github.com/teamradish/TRTwitchPlaysBot/commit/48dc0c0e344ce4e5cfc56002c44132a191f4b531.
