### ISSUE TITLE
Cannot get midinputdelay working

### ISSUE THREAD

**Issue by mrmwiebe** [teamradish/TRTwitchPlaysBot#38]
I would love for it to be possible to do something like "right right", and after looking at the FAQ and setting midinputdelayenabled to 1 and midinputdelay to 250 (same as global input delay), it still doesn't accept two inputs of the same direction so it feels like it's a bug.  

I've even tried "left #200ms left" and it doesn't work anymore.  Is that because i've enabled midinputdelay?  Please help!

**Comment by tdeeb** [comment]
Hey @mrmwiebe, thanks for your issue. Which operating system are you on?

There isn't currently a setting or permission ability named "midinputdelay" or "midinputdelayenabled" - does it work if you set [global_mid_input_delay_enabled](https://github.com/teamradish/TRTwitchPlaysBot/blob/master/Wiki/Settings-Documentation.md#global_mid_input_delay_enabled) to 1 instead and [global_mid_input_delay_time](https://github.com/teamradish/TRTwitchPlaysBot/blob/master/Wiki/Settings-Documentation.md#global_mid_input_delay_time) to 250?

**Comment by mrmwiebe** [comment]
hey @tdeeb !  Thanks for the quick response :D 

I'm using latest versions of Windows 10.  Ah yes sorry those are the two settings that I was using my apologies.  Yes, if i set global_mid_input_delay_enabled to 1 and global_mid_input_delay_time to 250 in the database, typing in two inputs like "right right" still doesn't work for me.

**Comment by tdeeb** [comment]
Do you have a `usermidinputdelay` user ability? This overrides the global value per-user. Type `!userabilities` and check if it's enabled. If so, disable it and see if that helps.

Just to clarify: are you using the latest 2.0 build?

**Comment by mrmwiebe** [comment]
yes i'm using the latest 2.0 release!  I just tried disabling the midinputdelay ability to no avail.  I can't tell if it's enabled or not.  I think it's off?

<img width="404" alt="firefox_2020-12-15_17-18-06" src="https://user-images.githubusercontent.com/2886831/102292196-88edd980-3ef9-11eb-99e1-d70675f23351.png">

**Comment by tdeeb** [comment]
The user-specific ability name is `usermidinputdelay`. `setmidinputdelay` determines if you can set the delay through the command (Ex. "!midinputdelay true 250"). I see that you don't have the ability, so that's not it. If it were disabled, there'd be "(disabled)" next to the name.

However, I noticed something off - the first command should have triggered a usage message since there needs to be a minimum of three arguments, the first being the username.

I suggest the next steps:
1. Type "!midinputdelay" to confirm the values.
2. Make sure the database you modified is the same path as the one the bot is using.
3. If the above two don't help, set "client_service_type" to 0 and restart the bot, then do everything in the console window. You may have ran into an exception, and TwitchLib sometimes makes it hard to catch them them.

And last question for now; sorry if I'm overloading you: was this database imported from a previous install or generated fresh?

**Comment by mrmwiebe** [comment]
No problem!  Happy to help debug if possible :)

1. I did and here's what it output `The global mid input delay is enabled with a duration of 250 milliseconds!`
2. I double checked and it is.  I've been making a lot of edits to the database and it's been working otherwise.
3. Ok, did this and this is what I got:
![obs64_59lhipahWm](https://user-images.githubusercontent.com/2886831/102396671-9eaedd80-3f91-11eb-8f55-dffd884892fd.png)
It doesn't seem to want to connect to my channel when "client_service_type" is set to 0.  Setting it back to 1 and it connects just fine.

**Comment by tdeeb** [comment]
When `client_service_type` is 0, TRBot runs locally in the same console window. You should be able to type commands in the console window and press enter them.

**Comment by mrmwiebe** [comment]
Ah ok!  Yes, now i get that usage message that you mention above.  I tried disabling the midinput and I see the (disabled) tag now, but rr still only outputs one keypress, where rl inputs right left in succession.

<img width="847" alt="vncviewer_2020-12-16_15-27-57" src="https://user-images.githubusercontent.com/2886831/102418789-4c7eb400-3fb3-11eb-972d-ac899d7258be.png">

**Comment by tdeeb** [comment]
Hmm, this requires further debugging:
1. Have you had success compiling from source? If so, add the following code [at this line](https://github.com/teamradish/TRTwitchPlaysBot/blob/cae648a286c20009e1aca096d092496b2b4a4019/TRBot/TRBot.Main/BotProgram.cs#L652) so we can see what it's really parsing in the console:
```
Console.WriteLine("\nReverse Parsed (post-process): " + ReverseParser.ReverseParse(inputSequence, usedConsole,
    new ReverseParser.ReverseParserOptions(ReverseParser.ShowPortTypes.ShowNonDefaultPorts, defaultPort,
    ReverseParser.ShowDurationTypes.ShowNonDefaultDurations, defaultDur)));
```
2. Send the input information for your "r" and "l" inputs with "!inputs r" and "!inputs l", respectively. If you're not on the console you're testing this with, switch to it or add it as the first argument (Ex. "!inputs myconsole r" and "!inputs myconsole l"). 

This highlights the need for a "debug_mode" setting in the database so TRBot can print more details to the console without the need to recompile.

**Comment by mrmwiebe** [comment]
Ok, I'll give that a try tomorrow!  I haven't done compiling from source yet, I'll check it out.  Yeah sounds like a debug mode would be handy heh. :)

**Comment by mrmwiebe** [comment]
Ok, tried building but it spit out an error:

![cmd_WVXJ9AwWer](https://user-images.githubusercontent.com/2886831/102655157-ae135f80-4126-11eb-85a4-9401484ab8de.png)

I believe i have it in the right spot:

![devenv_mZJU2nt7xE](https://user-images.githubusercontent.com/2886831/102655208-c4b9b680-4126-11eb-93e4-642768371e34.png)

**Comment by tdeeb** [comment]
Sorry, I made a few changes before adding that code. Go up to the start of the try-catch when parsing and move `defaultPort` and `defaultDur` above it.

**Comment by mrmwiebe** [comment]
No prob!  I figured it out :) 

Ok here's what happens when i input "uu", "ul", "rr", and "udlr" (max duration is intentionally very low rn)

![TRBot Main_fsxVk5shKK](https://user-images.githubusercontent.com/2886831/102657179-16b00b80-412a-11eb-9f11-2e92e59e7dcd.png)

**Comment by tdeeb** [comment]
I'm not sure why it's only complaining about the max duration on the last one - all input sequences in that image are the same duration.

Do you mind sending over your database file so I can take a look? Please omit anything from it that you consider personal.

**Comment by mrmwiebe** [comment]
Sure thing!  Just deleted user data.

[TRBotData.zip](https://github.com/teamradish/TRTwitchPlaysBot/files/5718552/TRBotData.zip)

**Comment by tdeeb** [comment]
Oh, I see the issue now - the mid input delay requires a blank input for the current console, and yours is lacking one. It needs one so it can use it as the blank input to substitute. I'll make this more clear in the documentation and with the new debug mode setting.

In short, to fix your issue do: "!addinput necrodancer # 0 0 0 0 0 0". You can substitute the "#" for any other input; the important value is the 4th argument (3rd zero), which specifies the input type.

**Comment by mrmwiebe** [comment]
That did it!  I guess I was being too ruthless in cleaning up the database to just what i needed.  Thank you for all your help and for this amazing tool! :)
