### ISSUE TITLE
[BUG] Bot doesn't get renamed

### ISSUE THREAD

**Issue by mrmwiebe** [teamradish/TRTwitchPlaysBot#43]
It seems that even though I have a name in the TwitchLoginSettings text file to rename the bot, it only ever uses the name of the channel it's connected to.  Is there a setting or something I need to change to make this work?

Thanks!

**Comment by tdeeb** [comment]
The `BotName` is the name of the account connecting to Twitch, whereas the `ChannelName` is the name of the channel to connect to with that account. Are you referring to renaming the account?

**Comment by mrmwiebe** [comment]
Ah I think I misunderstood what BotName is for.  I thought it would name the bot to something else but realizing now that would not be possible on Twitch.  But could I make an account with a bot name and then use that for BotName?

**Comment by tdeeb** [comment]
That's correct; you can even use your own account if you wish!

**Comment by tdeeb** [comment]
@mrmwiebe Is this resolved?

**Comment by mrmwiebe** [comment]
Yep!  Thanks for the reminder
