### ISSUE TITLE
[SUGGESTION] Levelling System

### ISSUE THREAD

**Issue by mrmwiebe** [teamradish/TRTwitchPlaysBot#46]
Just an idea I had.  At first I thought that users would keep levelling up after getting whitelisted as they type in more moves in chat, so I set up the command unlocks to unlock the more that players interacted in the chat.  Now I realize that it only happens with level 10, which makes sense.  

But, it could be cool if there was a way to set it up so that users can keep gaining "xp" as they type in commands and levelling up gradually?  Of course, it would be nice to be able to set level max and at how many messages or time in chat it takes to move to the next level.  Like right now i'd probably set it to level 30 max and it takes much longer to get to lv30.

Of course, just a suggestion, feel free to take it or leave it :)

**Comment by tdeeb** [comment]
This was originally designed with troll-prevention in mind. Often in my experience running/playing on streams, someone would come in and intentionally disrupt the game by overwriting a savestate. To mitigate this, savestates were limited to certain access levels, which users can be granted after enough activity in chat.

It's currently possible to change the level they promote to via [auto_promote_level](https://github.com/teamradish/TRTwitchPlaysBot/blob/master/Wiki/Settings-Documentation.md#auto_promote_level) and the input requirement via [auto_promote_input_req](https://github.com/teamradish/TRTwitchPlaysBot/blob/master/Wiki/Settings-Documentation.md#auto_promote_input_req). Leveling up users would mean they gain more permissions and thus access levels.

It can be done, but seems lower in priority to me in comparison to some of the other issues currently active (especially with my time budget). Out of curiosity, how do you intend to improve the stream using this? Is it to increase player retention?

**Comment by mrmwiebe** [comment]
Yeah it's intended to increase player retention, but also autonomy.  Since it's a 24h stream, giving the players a bit more agency while we're sleeping seems like a good idea.  And there might be a moment where there's no one in the chat that I've manually promoted who can't change the message cause i've set it to lv20 (so it doesn't get trolled).  It seems to be working now since there's people in the chat who i've promoted.

But yes, this is just a thought and def lower priority!

**Comment by tdeeb** [comment]
This sounds like a good use-case of the permission ability system. Users at level 20 (VIP) can set the game message because they're granted the `setgamemessage` ability at that level. It's possible to grant users at a lower level the same ability without also giving them other abilities by using "!toggleability".

Unfortunately, there's currently no way to grant individual abilities at certain input values; the best way to accomplish this involves modifying the `MinLevelToGrant` columns of a given permission ability in the `PermissionAbilities` table in the database.

**Comment by tdeeb** [comment]
Let's continue this discussion on the [associated issue in the new main repository](https://codeberg.org/kimimaru/TRBot/issues/41).
