### ISSUE TITLE
[SUGGESTION] arm builds for raspberrypi?

### ISSUE THREAD

**Issue by itsdarklikehell** [teamradish/TRTwitchPlaysBot#51]
Would like the possebility of building on armhf or arm64.

**Comment by tdeeb** [comment]
Hi @itsdarklikehell, thanks for the suggestion. .NET 5 supports arm64 for various operating systems, so it should be possible to build TRBot for one of these platforms.

In the case of the Raspberry Pi, you can try the [`debian.10-arm64`](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.NETCore.Platforms/pkg/runtime.json#L679) RID if you're running Debian or Raspbian. There are also RIDs for Alpine, Fedora, Ubuntu, and many others. Unfortunately, there aren't RIDs for armv7l or armhf yet.

To make a Debian build for arm64, the build command from the CLI in the TRBot.Main folder would be: `dotnet publish -c Release -o TRBot --self-contained --runtime debian.10-arm64`

I tried building myself just now and it succeeded, but I don't have a device to test on. Are you able to try it out?

Lastly, if you don't mind sharing, how do you intend to use TRBot on a Pi? I'm open to helping improve the experience.

**Comment by tdeeb** [comment]
@itsdarklikehell Have you had any success following my steps above?

**Comment by tdeeb** [comment]
Hi @itsdarklikehell, good news: I have received confirmation that TRBot runs on a Raspberry Pi 4B on Ubuntu 20.04 64-bit (arm64/aarch64)!

The following command should produce a runnable build, provided you have a .NET 5 or .NET Core install that supports this operating system (the latest will do): `dotnet publish -c Release -o TRBotArm64 --self-contained --runtime ubuntu.20.04-arm64`. Replace the "ubuntu.20.04" with the RID of your operating system.

As I mentioned above, you will also need to recompile the native uinput code to run on this architecture. Move the [`SetupVController.c` and SetupVController.h files`](https://github.com/teamradish/TRTwitchPlaysBot/tree/master/TRBot/TRBot.VirtualControllers/Native) onto your pi and install `gcc` if it's not installed. Then, compile the code, **on your pi**, as following: `gcc -fPIC -shared SetupVController.c -o SetupVController.so`.

Replace the `SetupVController.so` file in your pi's TRBot folder with the new one and you should be good to go!

**Comment by tdeeb** [comment]
Closing this issue as ARM builds are available via the instructions above.

**Comment by itsdarklikehell** [comment]
:+1:
