### ISSUE TITLE
[QUESTION] "Bot disconnected! please check your internet connection"

### ISSUE THREAD

**Issue by Estacaco** [teamradish/TRTwitchPlaysBot#52]
Hello, I've been trying to play around with TRBot but I can't seem to get it to connect
![TRbot](https://user-images.githubusercontent.com/44181620/105644707-8c5f7380-5e5c-11eb-84ca-58dfde84301f.png)

I've added firewall exceptions, I've turned off my firewall, I've tried running it as an Administrator all with no luck.

**Comment by tdeeb** [comment]
Hi @Estacaco, thanks for your report. Here are a few questions I have:

- Does the channel you're attempting to connect to exist?
- Are you running on ethernet or wifi?
- Is there some sort of block on Twitch (Ex. hosts/pi-hole)?
- Are you using an OAuth token for the password? Your raw password for the account will not work. You can generate one [here](https://twitchapps.com/tmi/).

**Comment by Estacaco** [comment]
The channel does exist.
I'm using ethernet
I'm not using any sort of filtering or blocks.
I'm not using OAuth

**Comment by Estacaco** [comment]
Generating an OAuth fixed it, thank you!

**Comment by tdeeb** [comment]
Awesome; I'm glad it worked :+1: !
