### ISSUE TITLE
DLL vJoy Problem 

### ISSUE THREAD

**Issue by ShelyGanz** [teamradish/TRTwitchPlaysBot#7]
Problem to connect 
[Link to scrennshot](https://prnt.sc/sxsrvj)

**Comment by tdeeb** [comment]
The disconnection message indicates the bot lost connection to the channel it's attempting to join. vJoy looks fine based on the logs, as it acquired the device.

Did you specify a valid channel name, bot name, and password in **LoginInfo.txt**?

**Comment by tdeeb** [comment]
@ShelyGanz Have you had any luck resolving the issue?

**Comment by tdeeb** [comment]
Closed due to inactivity. If the problem arises again, please file a new issue.
